### ISSUE TITLE
RX580 issue with H.265 10Bit.

### ISSUE THREAD

**Issue by TERMINATOR461997** [rigaya/VCEEnc#34]
So I recently updated to 2.8.0 from 2.5.0 and my settings where using a RX580 with VBR @10000 on some 4k 10Bit video.  2.5.0 would just start the encoding and have no issues. 2.8.0 on the other hand throws an error for the 580 not supporting 10Bit H.265/HVEC encoding... Does that mean the card will do 8Bit .265 and not 10bit? Seems strange that the older VCEEnc 6.10 would use a GPU that cant encode 10bit color, in a Bit10 setting. The exact error is this:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Error Video encoding (v2.8.0)

Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

VCEEnc 6.13

"C:\Program Files\StaxRip-v2.8.0-x64\Apps\Encoders\VCEEnc\VCEEncC64.exe" --avsdll "C:\Program Files\StaxRip-v2.8.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --codec hevc --output-depth 10 --quality slow --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --vbr 10000 -i "Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test).avs" -o "Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test)_out.hevc"

----------------------------------------------------------------------------------------------------------------------------------------------------------------
Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test)_out.hevc
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Error (clGetDeviceIDsFromD3D11KHR): device not found.
device #1: Failed to find d3d11 device.
GPU #0 (Radeon RX 580) does not support 10bit depth H.265/HEVC decoding.
Finished with error in VCEEncC.

StaxRip.ErrorAbortException: Video encoding returned exit code: 1 (0x1)


--------------------------- Video encoding ---------------------------

VCEEnc 6.13

"C:\Program Files\StaxRip-v2.8.0-x64\Apps\Encoders\VCEEnc\VCEEncC64.exe" --avsdll "C:\Program Files\StaxRip-v2.8.0-x64\Apps\FrameServer\AviSynth\AviSynth.dll" --codec hevc --output-depth 10 --quality slow --colormatrix bt2020nc --colorprim bt2020 --transfer smpte2084 --vbr 10000 -i "Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test).avs" -o "Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test)_out.hevc"

----------------------------------------------------------------------------------------------------------------------------------------------------------------
Z:\Harry Potter and the Order of the Phoenix (2007) (2160p BluRay x265 10bit HDR)_temp\Harry Potter and the Order of the Phoenix (Staxrip 2.8.0 Test)_out.hevc
----------------------------------------------------------------------------------------------------------------------------------------------------------------
Error (clGetDeviceIDsFromD3D11KHR): device not found.
device #1: Failed to find d3d11 device.
GPU #0 (Radeon RX 580) does not support 10bit depth H.265/HEVC decoding.
Finished with error in VCEEncC.


   at StaxRip.Proc.Start() in D:\Code\Github\staxrip\staxrip\Source\General\Proc.vb:line 361
   at StaxRip.VCEEnc.Encode() in D:\Code\Github\staxrip\staxrip\Source\Encoding\VCEEnc.vb:line 77
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Code\Github\staxrip\staxrip\Source\General\GlobalClass.vb:line 371

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Thanks for your time, in the meantime I'm going to try a driver update to 21.7.2 or whatever the recent one is.

**Comment by nyanmisaka** [comment]
Only dGPU >= RX 5000 series(Navi), APU >= ryzen 4000/5000 series(Renoir/Cezanne) can encode in 10-bit format(P010).

Remove the ` --output-depth 10` or just specify ` --output-depth 8`.

**Comment by rigaya** [comment]
Thanks @nyanmisaka, RX5xx has the same engine as RX4xx has and have no support for HEVC 10bit encoding, so the error message here is correct.
```
GPU #0 (Radeon RX 580) does not support 10bit depth H.265/HEVC decoding.
```
